[package]
name = "gpu-market"
version = "0.1.0"
description = "CME-style bounded-liquidity GPU index exchange on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gpu_market"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = "0.32.1"
